### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by bcndanos** [o0ragman0o/ITT#2]
I was reviewing the LIbCLL.sol and I saw that to find the next or the previous node, you have to look up into a mapping of booleans, 

```
struct CLL{
    mapping (uint => mapping (bool => uint)) cll;
}
```

I was wondering why you didn't use a structure for that:

```
struct CLL_Node {
   uint prev;
   uint next;
}
struct CLL {
    mapping (uint => CLL_Node) cll;
}
```

Then I changed the code and I tested a bunch of operations with the new structure. It's slightly cheaper, about 2% less gas cost.  I have the code in my computer.
If you thing it's important and your are interested in this change I can do a Pull Request with that.

**Comment by o0ragman0o** [comment]
I initially did and also had a slot for node data in the struct as well.  But for my application I found that dereferencing became cumbersome and so wanted to strip the library back to bare basics and use it simply as an indexing mechanism.

It then became clear that list navigation can be reduced to simple boolean logic which is used quite extensively in the ITT contract, but which can't be done with struct identifiers.

**Comment by bcndanos** [comment]
Yes, I see what you say.
Ok, I close the issue.
