### ISSUE TITLE
Instantaneous withdraw

### ISSUE THREAD

**Issue by bcndanos** [o0ragman0o/ITT#3]
I know I'm a pain in the neck :)
One thing that confused me in the ITTDesk is having an ether balance in the ITT contract.
What do you think of having a call to a new function to withdraw the ether balance after each successful trade operation?

This new function uses the xxxx.send(...) function, not .call, to avoid OOG. The .send function only send about 2.300 gas. If that withdraw fails (The recipient is a contract with a fallback function, etc..) you continue with the execution keeping the ether_balance and the user needs to withdraw manually.

Example:

```
    function safeNewSend(address _recipient, uint _ether)
        internal
        preventReentry()
        returns (bool)
    {
        return _recipient.send(_ether);
    }
```

```
function trade (uint _price, uint _amount, bool _side, bool _make) internal {
        ...
        balance[msg.sender] = tmsg.balance;
        //etherBalance[msg.sender] = tmsg.etherBalance;
        etherBalance[msg.sender] = safeNewSend(msg.sender, tmsg.etherBalance) ? 0 : tmsg.etherBalance;
}
```

Edit:
The same in the cancel function:

```
function cancel(uint _price) external canEnter returns (bool)
    {
        ...
        etherBalance[msg.sender] = safeNewSend(msg.sender, tmsg.etherBalance) ? 0 : tmsg.etherBalance;
        return true;
    }
```

**Comment by o0ragman0o** [comment]
Having the ether balance on contract is required to keep the trade logic 'internal' which how the contract can be so efficient.  One big component of that efficiency is the internal `tradeMsg` struct which is responsible for caching the trade states.  Structs can't be passed on external calls as would be required if the ether were kept in a separate store.  However, for the sake of functional efficiency, I had to sacrifice `separation of concerns`.

As for withdrawals,  what you're proposing are push payments which are not only unpredictable, but in this case would falsely penalise the taker for managing other peoples money of which he has no business with. It also breaks the secure internalisation of and the atomicity of the trading logic.  You have to remember that every external call you make is a threat to your contract state, so it is better practice to keep them tightly constrained and not make external calls until your logic and state mutation is completed.  So you can see that push payments break both those secure principles.

On top of that, it's simply unnecessary complexity to provide two different payment methods when a single simple method is sufficient. To do so breaks atomicity and doubles your attack surface.

Cheers,  Don't feel bad at all about the questions and suggestions.  That's what code review is all about and again, I'm really appreciating that you're looking so deeply into it.  We need solid contract writers for Ethereum to succeed and I'll soon be looking for trusted collaborators that really know their shit.

**Comment by bcndanos** [comment]
Upps. I think the same as you. I'm sure I didn't explain well. (I'm not really good in English)
I know it's necessary having the ether balance on contract.
I meant that could be a good functionality having a first try to withdraw the owner's ether, and if it fails, then keep with the manual withdraw. That way, the contract has as little ether as possible. One of the biggest concerns after the DAO disaster...

**Comment by o0ragman0o** [comment]
It's unnecessary and forces the user to keep depositing money on every bid/buy when instead they can simply trade with the accumulated funds already on the contract.

I think the term 'refund' might be confusing and I should probably just label 'Withdraw Ether'
