### ISSUE TITLE
it seems that ITT interface only provides single buy price and single sell price

### ISSUE THREAD

**Issue by bezalel** [o0ragman0o/ITT#4]
is supporting multiple orders simultaneously hard to implement in contract?
is there good reason for supporting only singe price than multiple order prices?

**Comment by o0ragman0o** [comment]
A trader can place any number of orders at different prices, but only one order per price.

This is a constraint of way the orders are stored in the FIFO's and the mapping to `amounts`. It's most efficient and logical to handle a single packet of data to make/take/cancel.

Keys to the `amounts` mapping are a sha3 of the traders address and order price as this will be the same every time for the same price, then there is no way to distinguish multiple orders of a single trader at a single price.

Changing an order amount at a price will put the order at the back of the FIFO else there is a risk that a trader at the front of the queue might keep topping up the order amount and unfairly starve all other orders in the queue.

**Comment by bezalel** [comment]
OK, now I can undertand what you mean after reading (very hard) ITT contract code :) Thanks

**Comment by o0ragman0o** [comment]
Yes, it's shamefully complex logic but it does yield huge efficiency and
usability advantages over atomic order trades.
ant.
Thanks for looking.  Feel free to ask anything about the code you want.

**Comment by bezalel** [comment]
No shame on your code! It's succinct and beautiful contract code :)
