### ISSUE TITLE
wrong price, buyer and seller field of Sale event

### ISSUE THREAD

**Issue by bezalel** [o0ragman0o/ITT#5]
It seems that next order's price is logged on "Sale" event

line 440 of ITT.sol
`              // prep for next order`
`            bestPrice = spread(!tmsg.side);`
`            Sale (bestPrice, takeAmount, msg.sender, maker);`

I think Sale event should be fired before going to next order

`          Sale (bestPrice, takeAmount, msg.sender, maker);`
`            // prep for next order`
`            bestPrice = spread(!tmsg.side);`

**Comment by o0ragman0o** [comment]
Yes, is bug.  Thanx!  Explains a lot about the trouble I was having with events in web3.js

**Comment by bezalel** [comment]
And I think buyer and seller fields are also wrong

**Comment by o0ragman0o** [comment]
I'll push the fix later just in case you find anything else.

**Comment by o0ragman0o** [comment]
In what way?

**Comment by bezalel** [comment]
buyer and seller should be adjusted for Take-Sell-Order and Take-Buy-Order cases each

            if (tmsg.side) {
              Sale (bestPrice, takeAmount, maker, msg.sender);
            } else {
              Sale (bestPrice, takeAmount, msg.sender, maker);
            }

**Comment by o0ragman0o** [comment]
'Sell' and 'Buy' are not the same as 'take' and 'make'.  The `Sale` event logs in the order of 'taker', 'maker', as I couldn't think of a good enough reason to implement `Buy`, `Sell` events when trade data is really only interested in sale price.

Happy to reconsider no a good argument.

**Comment by bezalel** [comment]
If your intention is logging taker and maker,
=> Sale (uint indexed price, uint amount, address indexed taker, address indexed maker);
how can client-side using web3 distinguish who takes Token and who takes Ether...?

Take-Sell-Order => taking made-sell order (give Ether and get Token)
Take-Buy-Order => taking made-buy order (give Token and get Ether)

**Comment by bezalel** [comment]
And why not logging Ether price for Sale event?
Can client-side track each order's ether price value?

**Comment by o0ragman0o** [comment]
`bestPrice` is the ether price

**Comment by o0ragman0o** [comment]
I think I should just add `side` to the Sale event to allow client to resolve buyer/seller

**Comment by bezalel** [comment]
I think Sale event should be distinguished whether it is Sell order or Buy order.
If Sell order is taken, market is going upward
If Buy order is taken, market is going downward
I think these information should be provided to traders

**Comment by bezalel** [comment]
"I think I should just add side to the Sale event to allow client to resolve buyer/seller"
 => Yes, I think so, and Sale event signature should be changed to =>
Sale (uint indexed price, uint amount, address indexed taker, address indexed maker, bool side);

**Comment by o0ragman0o** [comment]
Which can be done by including `side` in the `Sale` event.  It is much easier for the client to handle one historical collection than two which it would have to stitch together for something like a chart.

**Comment by bezalel** [comment]
But isn't it too complicated or impossible for client side to determine because there is no unique identifier for each orders and only price and trader(maker?) information on client side..
But it could be possible to implement on client side... I don't know exactly because I have not implemented client side yet :)

**Comment by o0ragman0o** [comment]
I'm not so experienced in `mongodb`, but the standard practice is to pull events into persistant storage mongodb which which can be filtered for things like the `side` bool which will give all events one way or the other.

**Comment by o0ragman0o** [comment]
Fixed next price before `Sale` event. Added `bool tmsg.side`
