### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by tradebit-x** [o0ragman0o/ITT#9]
Pls dear, thanks for your product you are doing a great job, but please how do one install your codes or script on a site so it works perfectly? thanks

**Comment by o0ragman0o** [comment]
This is an Ethereum smart contract library requiring knowledge of Solidity and DAPP development.  It is not a script for a website.

**Comment by tradebit-x** [comment]
Thanks a lot for your response I so much appreciate, I know about the solidity stuff and I can see the etc codes In it but what motivated me is the in built trade engine it has, now I can create a token on solidity with that code but the problem is where or how to apply the code for the trading , and relate it to a site where users can make purchase or trade the token. I would so Much appreciate your guild line especially on the trade engine implementation. Thanks once again for your kind heartedness

**Comment by o0ragman0o** [comment]
This is not a technical issue and so has been closed. Please don't use github issues to solicit general advice.

**Comment by tradebit-x** [comment]
Okay, noted, hear is my email, support@prowebsitedev.com u can help me learn ur code Better
